# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from manager.grpc import sensor_pb2 as sensor__pb2


class SensorServiceStub(object):
    """─────────────────────────────────────────────────────────────────────────────
    SensorService — the sole communication channel between Sensor and Manager.
    All connections are INITIATED by the Sensor (outbound-only).
    All connections use mutual TLS (mTLS).
    ─────────────────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Join = channel.unary_unary(
                '/otrap.sensor.v1.SensorService/Join',
                request_serializer=sensor__pb2.JoinRequest.SerializeToString,
                response_deserializer=sensor__pb2.JoinResponse.FromString,
                )
        self.EventStream = channel.stream_stream(
                '/otrap.sensor.v1.SensorService/EventStream',
                request_serializer=sensor__pb2.SensorEvent.SerializeToString,
                response_deserializer=sensor__pb2.ManagerCommand.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/otrap.sensor.v1.SensorService/Heartbeat',
                request_serializer=sensor__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=sensor__pb2.HeartbeatResponse.FromString,
                )
        self.SyncMemoryWrite = channel.unary_unary(
                '/otrap.sensor.v1.SensorService/SyncMemoryWrite',
                request_serializer=sensor__pb2.MemoryWriteRequest.SerializeToString,
                response_deserializer=sensor__pb2.MemoryWriteResponse.FromString,
                )


class SensorServiceServicer(object):
    """─────────────────────────────────────────────────────────────────────────────
    SensorService — the sole communication channel between Sensor and Manager.
    All connections are INITIATED by the Sensor (outbound-only).
    All connections use mutual TLS (mTLS).
    ─────────────────────────────────────────────────────────────────────────────
    """

    def Join(self, request, context):
        """Join: one-time registration with a JOIN_TOKEN.
        Manager validates token, issues mTLS client cert, returns config.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EventStream(self, request_iterator, context):
        """EventStream: long-lived bidirectional stream.
        Sensor sends events continuously; Manager sends commands back.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat: unary RPC sent every 30 seconds.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncMemoryWrite(self, request, context):
        """SyncMemoryWrite: sensor reports an S7 DB write for forensic recording.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Join': grpc.unary_unary_rpc_method_handler(
                    servicer.Join,
                    request_deserializer=sensor__pb2.JoinRequest.FromString,
                    response_serializer=sensor__pb2.JoinResponse.SerializeToString,
            ),
            'EventStream': grpc.stream_stream_rpc_method_handler(
                    servicer.EventStream,
                    request_deserializer=sensor__pb2.SensorEvent.FromString,
                    response_serializer=sensor__pb2.ManagerCommand.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=sensor__pb2.HeartbeatRequest.FromString,
                    response_serializer=sensor__pb2.HeartbeatResponse.SerializeToString,
            ),
            'SyncMemoryWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncMemoryWrite,
                    request_deserializer=sensor__pb2.MemoryWriteRequest.FromString,
                    response_serializer=sensor__pb2.MemoryWriteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'otrap.sensor.v1.SensorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SensorService(object):
    """─────────────────────────────────────────────────────────────────────────────
    SensorService — the sole communication channel between Sensor and Manager.
    All connections are INITIATED by the Sensor (outbound-only).
    All connections use mutual TLS (mTLS).
    ─────────────────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def Join(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/otrap.sensor.v1.SensorService/Join',
            sensor__pb2.JoinRequest.SerializeToString,
            sensor__pb2.JoinResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EventStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/otrap.sensor.v1.SensorService/EventStream',
            sensor__pb2.SensorEvent.SerializeToString,
            sensor__pb2.ManagerCommand.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/otrap.sensor.v1.SensorService/Heartbeat',
            sensor__pb2.HeartbeatRequest.SerializeToString,
            sensor__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SyncMemoryWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/otrap.sensor.v1.SensorService/SyncMemoryWrite',
            sensor__pb2.MemoryWriteRequest.SerializeToString,
            sensor__pb2.MemoryWriteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
