// This file is auto-generated by protoc.
// Run: make proto
//
// Required tools:
//   apt install protobuf-compiler
//
// Generation command (from repo root):
//   protoc -I=proto \
//     --go_out=sensor/proto/sensorv1 \
//     --go_opt=paths=source_relative \
//     --go-grpc_out=sensor/proto/sensorv1 \
//     --go-grpc_opt=paths=source_relative \
//     proto/sensor.proto
//
// Generated stubs are committed to the repo so normal builds do not need codegen.
// Use make proto only when proto/sensor.proto changes.

package sensorv1
