// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: sensor.proto

package sensorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SensorService_Join_FullMethodName            = "/otrap.sensor.v1.SensorService/Join"
	SensorService_EventStream_FullMethodName     = "/otrap.sensor.v1.SensorService/EventStream"
	SensorService_Heartbeat_FullMethodName       = "/otrap.sensor.v1.SensorService/Heartbeat"
	SensorService_SyncMemoryWrite_FullMethodName = "/otrap.sensor.v1.SensorService/SyncMemoryWrite"
)

// SensorServiceClient is the client API for SensorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SensorServiceClient interface {
	// Join: one-time registration with a JOIN_TOKEN.
	// Manager validates token, issues mTLS client cert, returns config.
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	// EventStream: long-lived bidirectional stream.
	// Sensor sends events continuously; Manager sends commands back.
	EventStream(ctx context.Context, opts ...grpc.CallOption) (SensorService_EventStreamClient, error)
	// Heartbeat: unary RPC sent every 30 seconds.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// SyncMemoryWrite: sensor reports an S7 DB write for forensic recording.
	SyncMemoryWrite(ctx context.Context, in *MemoryWriteRequest, opts ...grpc.CallOption) (*MemoryWriteResponse, error)
}

type sensorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSensorServiceClient(cc grpc.ClientConnInterface) SensorServiceClient {
	return &sensorServiceClient{cc}
}

func (c *sensorServiceClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, SensorService_Join_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorServiceClient) EventStream(ctx context.Context, opts ...grpc.CallOption) (SensorService_EventStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &SensorService_ServiceDesc.Streams[0], SensorService_EventStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &sensorServiceEventStreamClient{stream}
	return x, nil
}

type SensorService_EventStreamClient interface {
	Send(*SensorEvent) error
	Recv() (*ManagerCommand, error)
	grpc.ClientStream
}

type sensorServiceEventStreamClient struct {
	grpc.ClientStream
}

func (x *sensorServiceEventStreamClient) Send(m *SensorEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sensorServiceEventStreamClient) Recv() (*ManagerCommand, error) {
	m := new(ManagerCommand)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sensorServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, SensorService_Heartbeat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorServiceClient) SyncMemoryWrite(ctx context.Context, in *MemoryWriteRequest, opts ...grpc.CallOption) (*MemoryWriteResponse, error) {
	out := new(MemoryWriteResponse)
	err := c.cc.Invoke(ctx, SensorService_SyncMemoryWrite_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SensorServiceServer is the server API for SensorService service.
// All implementations must embed UnimplementedSensorServiceServer
// for forward compatibility
type SensorServiceServer interface {
	// Join: one-time registration with a JOIN_TOKEN.
	// Manager validates token, issues mTLS client cert, returns config.
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	// EventStream: long-lived bidirectional stream.
	// Sensor sends events continuously; Manager sends commands back.
	EventStream(SensorService_EventStreamServer) error
	// Heartbeat: unary RPC sent every 30 seconds.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// SyncMemoryWrite: sensor reports an S7 DB write for forensic recording.
	SyncMemoryWrite(context.Context, *MemoryWriteRequest) (*MemoryWriteResponse, error)
	mustEmbedUnimplementedSensorServiceServer()
}

// UnimplementedSensorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSensorServiceServer struct {
}

func (UnimplementedSensorServiceServer) Join(context.Context, *JoinRequest) (*JoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedSensorServiceServer) EventStream(SensorService_EventStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method EventStream not implemented")
}
func (UnimplementedSensorServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedSensorServiceServer) SyncMemoryWrite(context.Context, *MemoryWriteRequest) (*MemoryWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncMemoryWrite not implemented")
}
func (UnimplementedSensorServiceServer) mustEmbedUnimplementedSensorServiceServer() {}

// UnsafeSensorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SensorServiceServer will
// result in compilation errors.
type UnsafeSensorServiceServer interface {
	mustEmbedUnimplementedSensorServiceServer()
}

func RegisterSensorServiceServer(s grpc.ServiceRegistrar, srv SensorServiceServer) {
	s.RegisterService(&SensorService_ServiceDesc, srv)
}

func _SensorService_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServiceServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorService_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServiceServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorService_EventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SensorServiceServer).EventStream(&sensorServiceEventStreamServer{stream})
}

type SensorService_EventStreamServer interface {
	Send(*ManagerCommand) error
	Recv() (*SensorEvent, error)
	grpc.ServerStream
}

type sensorServiceEventStreamServer struct {
	grpc.ServerStream
}

func (x *sensorServiceEventStreamServer) Send(m *ManagerCommand) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sensorServiceEventStreamServer) Recv() (*SensorEvent, error) {
	m := new(SensorEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SensorService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorService_SyncMemoryWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServiceServer).SyncMemoryWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorService_SyncMemoryWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServiceServer).SyncMemoryWrite(ctx, req.(*MemoryWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SensorService_ServiceDesc is the grpc.ServiceDesc for SensorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SensorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "otrap.sensor.v1.SensorService",
	HandlerType: (*SensorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _SensorService_Join_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _SensorService_Heartbeat_Handler,
		},
		{
			MethodName: "SyncMemoryWrite",
			Handler:    _SensorService_SyncMemoryWrite_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventStream",
			Handler:       _SensorService_EventStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sensor.proto",
}
