#!/usr/bin/env bash
# OTrap Sensor Installer — standalone version
#
# EASY PATH (recommended):
#   Use the one-line install command from the OTrap Manager UI:
#   Sensors → Add Sensor → Generate → copy the "Install Command" and run it on the target host.
#
# MANUAL PATH (advanced):
#   Set the required env vars, then run this script directly:
#
#   SENSOR_MANAGER_URL=192.168.1.10:9443 \
#   SENSOR_JOIN_TOKEN=<single-use token>  \
#   SENSOR_NAME=my-sensor                \
#   SENSOR_CERT_ENC_KEY=<64-char hex>    \
#   bash install_sensor.sh
#
# Requirements: Docker 24+, git
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

OTRAP_MANAGER_URL="${SENSOR_MANAGER_URL:-}"
OTRAP_JOIN_TOKEN="${SENSOR_JOIN_TOKEN:-}"
OTRAP_SENSOR_NAME="${SENSOR_NAME:-otrap-sensor}"
OTRAP_CERT_ENC_KEY="${SENSOR_CERT_ENC_KEY:-}"
OTRAP_REPO_URL="${SENSOR_REPO_URL:-https://github.com/Janberkb/OTrap-v2-ICS-Honeypot-Intelligence-Platform.git}"
OTRAP_IMAGE="otrap-sensor:local"
OTRAP_BUILD_DIR="/tmp/otrap-sensor-build"
OTRAP_CERTS_DIR="/var/lib/otrap/sensor/certs"

# ─── Validation ───────────────────────────────────────────────────────────────
missing=()
[[ -z "$OTRAP_MANAGER_URL"  ]] && missing+=("SENSOR_MANAGER_URL")
[[ -z "$OTRAP_JOIN_TOKEN"   ]] && missing+=("SENSOR_JOIN_TOKEN")
[[ -z "$OTRAP_CERT_ENC_KEY" ]] && missing+=("SENSOR_CERT_ENC_KEY")
if [[ ${#missing[@]} -gt 0 ]]; then
    echo "Error: missing required env vars: ${missing[*]}" >&2
    echo "Set them manually or use the install command generated by the OTrap Manager UI." >&2
    exit 1
fi

# ─── Dependency checks ────────────────────────────────────────────────────────
for cmd in docker git; do
    command -v "$cmd" >/dev/null 2>&1 || { echo "Error: '$cmd' is not installed." >&2; exit 1; }
done

OTRAP_CONTAINER="otrap-sensor-$(echo "$OTRAP_SENSOR_NAME" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-' | sed 's/^-//;s/-$//' | cut -c1-40)"

echo "────────────────────────────────────────────"
echo "  OTrap Sensor Installer"
echo "  Sensor : $OTRAP_SENSOR_NAME"
echo "  Manager: $OTRAP_MANAGER_URL"
echo "────────────────────────────────────────────"
echo ""

# ─── Clone / update repo ──────────────────────────────────────────────────────
echo "[1/3] Fetching OTrap sensor source..."
if [ -d "$OTRAP_BUILD_DIR/.git" ]; then
    git -C "$OTRAP_BUILD_DIR" pull --ff-only --quiet
else
    git clone --depth=1 --quiet "$OTRAP_REPO_URL" "$OTRAP_BUILD_DIR"
fi

# ─── Build sensor image ───────────────────────────────────────────────────────
echo "[2/3] Building sensor Docker image (first run ~2 min)..."
docker build --quiet -t "$OTRAP_IMAGE" "$OTRAP_BUILD_DIR/sensor"
echo "      Build complete."

# ─── Run sensor container ─────────────────────────────────────────────────────
docker rm -f "$OTRAP_CONTAINER" >/dev/null 2>&1 || true
mkdir -p "$OTRAP_CERTS_DIR"

echo "[3/3] Starting sensor container: $OTRAP_CONTAINER"
docker run -d \
    --name  "$OTRAP_CONTAINER" \
    --restart unless-stopped \
    -p 102:102 \
    -p 502:502 \
    -p 80:80 \
    -p 443:443 \
    -v "$OTRAP_CERTS_DIR:/etc/otrap/sensor/certs" \
    -e "SENSOR_MANAGER_URL=$OTRAP_MANAGER_URL" \
    -e "SENSOR_JOIN_TOKEN=$OTRAP_JOIN_TOKEN" \
    -e "SENSOR_NAME=$OTRAP_SENSOR_NAME" \
    -e "SENSOR_CERT_ENC_KEY=$OTRAP_CERT_ENC_KEY" \
    -e SENSOR_INSECURE_JOIN=true \
    -e LOG_LEVEL=info \
    "$OTRAP_IMAGE"

echo ""
echo "────────────────────────────────────────────"
echo "  Sensor started. Waiting for join..."
echo "────────────────────────────────────────────"
sleep 4
docker logs "$OTRAP_CONTAINER" 2>&1 | tail -10 || true
echo ""
echo "Logs : docker logs -f $OTRAP_CONTAINER"
echo "Stop : docker stop $OTRAP_CONTAINER"
echo "The sensor will appear as active in the OTrap Manager UI within seconds."
