"""
manager/api/reports.py — Saved report CRUD endpoints.

Reports are data snapshots generated by the frontend and stored in the DB
so they can be retrieved, viewed, and deleted later.
"""
from __future__ import annotations

import uuid
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Response
from pydantic import BaseModel
from sqlalchemy import select, delete as sa_delete

from manager.api.auth import get_current_user
from manager.db import models
from manager.db.engine import get_db

router = APIRouter(prefix="/reports", tags=["reports"])
_SENSITIVE_REPORT_IOC_TYPES = {"username", "password"}


class ReportCreateRequest(BaseModel):
    title:       str
    range_label: str
    range_hours: int
    data:        dict[str, Any] | None = None


class BulkDeleteRequest(BaseModel):
    ids: list[str]


def _serialize_meta(r: models.Report) -> dict:
    """Return report metadata without the data blob (for list endpoint)."""
    return {
        "id":           str(r.id),
        "title":        r.title,
        "range_label":  r.range_label,
        "range_hours":  r.range_hours,
        "generated_at": r.generated_at,
    }


def _mask_report_ioc_value(ioc_type: str | None, value: Any) -> Any:
    if not isinstance(value, str):
        return value

    kind = (ioc_type or "").lower()
    if kind == "password":
        return "********"
    if kind == "username":
        if "@" in value:
            local, _, domain = value.partition("@")
            if len(local) <= 1:
                return f"*@{domain}" if domain else "*"
            if len(local) == 2:
                return f"{local[0]}*@{domain}" if domain else f"{local[0]}*"
            masked = f"{local[:2]}{'*' * max(len(local) - 2, 2)}"
            return f"{masked}@{domain}" if domain else masked
        if len(value) <= 1:
            return "*"
        if len(value) <= 3:
            return value[0] + ("*" * (len(value) - 1))
        return f"{value[:2]}{'*' * max(len(value) - 3, 2)}{value[-1]}"
    return value


def _sanitize_report_data(data: dict[str, Any] | None) -> dict[str, Any] | None:
    if data is None or not isinstance(data, dict):
        return data

    sanitized = dict(data)
    raw_iocs = sanitized.get("iocs")
    if isinstance(raw_iocs, list):
        safe_iocs = []
        for item in raw_iocs:
            if not isinstance(item, dict):
                safe_iocs.append(item)
                continue
            row = dict(item)
            kind = (row.get("ioc_type") or "").lower()
            row["value"] = _mask_report_ioc_value(kind, row.get("value"))
            if kind in _SENSITIVE_REPORT_IOC_TYPES:
                row["is_redacted"] = True
            safe_iocs.append(row)
        sanitized["iocs"] = safe_iocs
    return sanitized


def _serialize_full(r: models.Report) -> dict:
    meta = _serialize_meta(r)
    meta["data"] = _sanitize_report_data(r.data)
    return meta


@router.get("")
async def list_reports(db=Depends(get_db), user=Depends(get_current_user)) -> dict:
    reports = await models.Report.list_all(db)
    return {"items": [_serialize_meta(r) for r in reports]}


@router.post("", status_code=201)
async def create_report(
    payload: ReportCreateRequest,
    db=Depends(get_db),
    user=Depends(get_current_user),
) -> dict:
    if not payload.title.strip():
        raise HTTPException(status_code=400, detail="Title is required")
    if payload.range_hours not in (24, 168, 720):
        raise HTTPException(status_code=400, detail="range_hours must be 24, 168, or 720")

    report = models.Report(
        title=payload.title.strip(),
        range_label=payload.range_label,
        range_hours=payload.range_hours,
        data=_sanitize_report_data(payload.data),
    )
    db.add(report)
    await db.commit()
    await db.refresh(report)
    return _serialize_meta(report)


@router.get("/{report_id}")
async def get_report(
    report_id: str,
    db=Depends(get_db),
    user=Depends(get_current_user),
) -> dict:
    try:
        rid = uuid.UUID(report_id)
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid report ID")

    result = await db.execute(select(models.Report).where(models.Report.id == rid))
    report = result.scalar_one_or_none()
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")
    return _serialize_full(report)


@router.delete("/{report_id}")
async def delete_report(
    report_id: str,
    db=Depends(get_db),
    user=Depends(get_current_user),
) -> Response:
    try:
        rid = uuid.UUID(report_id)
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid report ID")

    result = await db.execute(select(models.Report).where(models.Report.id == rid))
    if not result.scalar_one_or_none():
        raise HTTPException(status_code=404, detail="Report not found")

    await db.execute(sa_delete(models.Report).where(models.Report.id == rid))
    await db.commit()
    return Response(status_code=204)


@router.post("/bulk-delete")
async def bulk_delete_reports(
    payload: BulkDeleteRequest,
    db=Depends(get_db),
    user=Depends(get_current_user),
) -> dict:
    if not payload.ids:
        return {"deleted": 0}

    uuids = []
    for raw in payload.ids:
        try:
            uuids.append(uuid.UUID(raw))
        except ValueError:
            raise HTTPException(status_code=400, detail=f"Invalid report ID: {raw}")

    result = await db.execute(
        sa_delete(models.Report).where(models.Report.id.in_(uuids))
    )
    await db.commit()
    return {"deleted": result.rowcount}
